# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "akarmyzov"
    encrypt = true
    key     = "terraform/states/hadoop-sandbox/./terraform.tfstate"
    region  = "eu-central-1"
  }
}
